- hosts: gui
  vars:
    - Port: 8080
    - Document_root: /var/www/html/
  tasks:
    - name: Installing httpd
      package:
        name: httpd
        state: present

    - name: Changing Webserver conf file
      template:
        dest: "/etc/httpd/conf.d/"
        src: "conf.d"
        
    - name: Restart HTTPD
      service:
        name: httpd
        state: restarted
      changed_when: false
    
