- hosts: 127.0.0.1
  tasks:      
    - command: "date"
      changed_when: false
        

    - command: "ls /home/prateek/lw1"
      register: x
      ignore_errors: yes

    - debug:
        var: x
    
    - command: " mkdir /home/prateek/lw1"
      ignore_errors: yes
      when: x.rc != 0
