- hosts: "127.0.0.1"
  tasks:
    block:
     - name: Print a message
       debug:
         msg: 'I execute normally'

     - name: Force a failure
       command: /bin/false

     - name: Never print this
       debug:
         msg: 'I never execute :-('
    rescue:
     - name: Print when errors
       ansible.builtin.debug:
         msg: 'I caught an error, can do stuff here to fix it, :-)'
  
    always:
     - name: Always do this
       debug:
         msg: "This always executes, :-)"


