- hosts: 127.0.0.1
  vars:
    # This works as a list of dictionaries
    - users:
        - name: "jack3"
          password: "fuck"
          group: "jack"

        - name: "jack4"
          password: "fuck"
          group: "jack"

  tasks:
    #Creating group
    - name: create user
      user:
        name: "jack1"
        password: "fuck"
        state: present

   # Addng user to a Group
    - name: creating and adding to group
      user:
        name: "jack2"
        password: "fuck | password_hash('sha512')"
        state: present
        group: "jack"
  
    - debug:
        var: users

    # Using loop
    - name: Using loops
      user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        state: present
        group: "{{ item.group }}"    
      loop: "{{ users }}"  
